runtime: python
env: flex
entrypoint: gunicorn -t 300  -b :$PORT my_project.wsgi
service: videoanalyser
runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  max_concurrent_requests: 1
  cpu_utilization:
    target_utilization: 0.4
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20